### ISSUE TITLE
myFridge.js

### ISSUE THREAD

**Issue by JeffreyJohnston** [meteorinaction/deprecated-ch02-fridge#2]
if (Meteor.isSever) is nested twice ... most likely cut and paste error but may confuse some. Made me look twice :)

**Comment by yauh** [comment]
Thanks, I'll clean up all repos shortly (probably create new ones from scratch) nd then get rid of this issue as well.

**Comment by yauh** [comment]
Fixed in the new repo: https://github.com/meteorinaction/ch02-myfridge
